"use server";

import { prisma } from "@/lib/prisma";
import { requireCompany, requirePermission } from "@/lib/rbac";
import { logActivity } from "@/lib/activity";

export async function checkReplenishmentRules() {
  const user = await requireCompany();
  await requirePermission("purchases:write");

  const companyId = user.companyId!;

  // 1. Find all products that have a preferred supplier and min stock level
  const products = await prisma.product.findMany({
    where: {
      companyId,
      minStockLevel: { gt: 0 },
      preferredSupplierId: { not: null },
      status: "ACTIVE"
    },
    include: {
      stockLevels: true
    }
  });

  let createdCount = 0;

  for (const product of products) {
    const totalStock = product.stockLevels.reduce((sum, level) => sum + level.quantity, 0);

    if (totalStock <= product.minStockLevel) {
      // 2. Check if a DRAFT or SENT PO already exists for this product to avoid duplicates
      const existingPO = await prisma.purchaseOrderItem.findFirst({
        where: {
          productId: product.id,
          po: {
            companyId,
            status: { in: ["DRAFT"] } // Changed to match POStatus ("DRAFT", "SUBMITTED", etc.)
          }
        }
      });

      if (!existingPO) {
        // 3. Create a Draft Purchase Order
        const sequence = await prisma.sequence.upsert({
          where: { companyId_type: { companyId, type: "PO" } },
          update: { value: { increment: 1 } },
          create: { companyId, type: "PO", value: 1 },
        });

        const poNumber = `PO-${new Date().getFullYear()}${String(new Date().getMonth() + 1).padStart(2, "0")}-${String(sequence.value).padStart(4, "0")}`;

        const qty = product.reorderQuantity && product.reorderQuantity > 0 
          ? product.reorderQuantity 
          : product.minStockLevel - totalStock + 10; // Default buffer

        const estimatedCost = product.averageCost ? Number(product.averageCost) : 0;
        const totalAmount = estimatedCost * qty;

        const po = await prisma.purchaseOrder.create({
          data: {
            companyId,
            poNumber,
            supplierId: product.preferredSupplierId!,
            status: "DRAFT",
            totalAmount,
            taxAmount: 0,
            currency: "USD",
            notes: "Auto-generated by Replenishment Rule",
            createdBy: user.id,
            items: {
              create: {
                productId: product.id,
                quantity: qty,
                unitPrice: estimatedCost,
                total: totalAmount
              }
            }
          }
        });

        await logActivity({
          companyId,
          userId: user.id,
          action: "CREATED",
          entityType: "PurchaseOrder",
          entityId: po.id,
          details: `Auto-generated replenishment PO for ${product.name}`
        });

        createdCount++;
      }
    }
  }

  return { success: true, message: `Checked replenishment rules. Created ${createdCount} draft Purchase Orders.` };
}
